btn_ok.bind('<Button-1>', lambda event: self.view.records(self.entry_description.get(), self.combobox.get(),)) TypeError: records() missing 4 required positional arguments: 'genre', 'time', 'regisseur', and 'artist'